export const env = {
  FIREBASE_API_KEY: import.meta.env.VITE_FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
  FIREBASE_PRODUCT_ID: import.meta.env.VITE_PRODUCT_ID,
  FIREBASE_FIREBASE_STORAGE_BUCKET: import.meta.env.FIREBASE_STORAGE_BUCKET,
  FIREBASE_FIREBASE_MESSAGING_SENDING_ID: import.meta.env.FIREBASE_MESSAGING_SENDING_ID,
  FIREBASE_FIREBASE_APP_ID: import.meta.env.VITE_FIREBASE_APP_ID,
  FIREBASE_FIREBASE_MEASUREMENT_ID: import.meta.env.VITE_FIREBASE_MEASUREMENT_ID,
}